version: '2'
services:
    rcp2-app:
        image: rcp2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rcp2-mysql:3306/rcp2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rcp2-mysql:
        extends:
            file: mysql.yml
            service: rcp2-mysql
